---
title: "Ocean Development Indicators in the R programming language"
author: "Dr Lucas Hertzog"
date: "2024-07-01"
site: bookdown::bookdown_site
documentclass: book
description: "A comprehensive guide on using R to extract, clean, and analyse data from the UN Global SDG Database."
---

# Welcome

Welcome to the course on Ocean Development Indicators in R. This book provides all the necessary materials and instructions.

## Context

Ocean accounting provides comprehensive indicators of mainstream ocean contributions to society, and the SDG indicators could be a starting point for highlighting gaps.

-   Identify which indicators are available in the context of the country.

-   Transboundary cooperation (starting point looking at other countries)

-   Open and freely accessible data.

## Training Objectives

-   Learn to extract, clean, and analyse UN Global SDG Database data using R and the UN SDG API.

-   Provide foundational knowledge on interacting with GitHub using R within the workshop context.

-   Enable participants to build indicators informed by global standards but tailored to their specific contexts.
